sudo: required

language: python

services:
  - docker

before_install:
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64 -o /usr/local/bin/goss
  - sudo chmod +rx /usr/local/bin/goss
  - cd contrib/docker
  - cp .env.template .env
  - docker-compose -f docker-compose-alpine.yml build 
  - docker-compose -f docker-compose-alpine.yml up -d db redis solr

install:
  # wait for db redis and solr. Could use nc?
  - sleep 180s
  - docker-compose -f docker-compose-alpine.yml up -d ckan
  - sleep 300s
  - docker logs ckan

script:
  - sudo goss --gossfile ../../goss.yaml validate --retry-timeout 180s --sleep 1s
  - docker logs ckan
